services:

  mysql:
    image: mysql:8.0
    container_name: buildsync-mysql

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10


  backend:
    build:
      context: ./backend

    container_name: buildsync-backend

    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

    depends_on:
      mysql:
        condition: service_healthy

    ports:
      - "8080:8080"


  frontend:
    build:
      context: ./frontend

    container_name: buildsync-frontend

    environment:
      VITE_API_URL: ${VITE_API_URL}

    depends_on:
      backend:
        condition: service_started


  nginx:
    image: nginx:latest

    container_name: buildsync-nginx

    ports:
      - "80:80"

    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_started

    restart: unless-stopped


volumes:
  mysql-data: