spring.application.name=backend

# DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Jwt
jwt.secret=buildsync-secret-key-2026-super-secure-key-must-be-long-enough
jwt.expiration=3600000

# SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tjdwns8083@gmail.com
spring.mail.password=ohdx xilu nubz asdr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com